### ISSUE TITLE
proxyquire used for?

### ISSUE THREAD

**Issue by molinto** [TalhaAwan/Express-Controller-Unit-Testing#1]
Hi, thanks for your blog article.

I have a similar but using Waterline ORM, what is proxyquire used for in package.json please?

**Comment by TalhaAwan** [comment]
Hi,

proxyquire is used for stubbing out (overriding) methods of a dependency. A good example is given of `path` module on the [official page](https://www.npmjs.com/package/proxyquire).

I think it's not being used in this example project though, so I'll remove it from package.json. Or feel free to submit a PR!

**Comment by molinto** [comment]
Hi, ok thanks.  I'm trying to do the same thing with proxyquire. Just wondered if it was required.
Closing
