### ISSUE TITLE
Use a later version of sinon

### ISSUE THREAD

**Issue by molinto** [TalhaAwan/Express-Controller-Unit-Testing#2]
Hi, I've cloned your repo, but it seems to be 3yrs out of date (on 31 Dec 2016).  Great to see a later version / project updated please.

**Comment by TalhaAwan** [comment]
Hi,

I'll try to update the packages soon. Or you can go ahead with the update and send me a PR to merge. Thanks.

**Comment by molinto** [comment]
Don't worry about it, not an issue. Thanks

Closing
